services:
  paulo-dev:
    build:
      context: .
      dockerfile: Dockerfile.paulo
    image: myapp:paulodev
    command: ["/bin/zsh", "-c", "source $HOME/.zshrc && tail -f /dev/null"]
    volumes:
      - ./test:/app/test
      - ./docs:/app/docs
      - ./libs:/app/libs
      - ./src:/app/src
      - ./include:/app/include
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - ./README.md:/app/README.md

      
