FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive


SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential \
    gcc \
    clang \
    cmake \
    gdb

WORKDIR /app

RUN mkdir build && \
    mkdir bin


