FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

ENV PATH="/app/bin:${PATH}"

RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential \
    curl \
    cmake \
    gdb \
    unzip \
    ca-certificates \
    libzmq3-dev \
    pkg-config \
    # Clean up apt cache to reduce image size
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir build && \
    mkdir bin 

WORKDIR /app
