services:
  prod-app:
    image: cpp_project
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]

  
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: myapp:dev
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./test:/app/test
      - ./docs:/app/docs
      - ./libs:/app/libs
      - ./src:/app/src
      - ./include:/app/include
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - ./README.md:/app/README.md

      
