FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential \
    gcc \
    cmake \

WORKDIR /app

COPY libs/ ./libs/
COPY test/ ./test/
COPY docs/ ./docs/
COPY CMakeLists.txt .
COPY README.md .
COPY include/ ./include/
COPY src/ ./src/


RUN mkdir build && \
    mkdir bin && \
    cd build && \
    cmake .. && \
    make

CMD ["./bin/hello"]
